version: '3.4'

services:
  db:
    image: postgres:16.0
    restart: always
    container_name: sozeris-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5433:5432
    #volumes:
    #  - ./db_data:/var/lib/postgresql/data
